// Generated by Selenium IDE
const { Builder, By, Key, until, WebDriver } = require('selenium-webdriver')
const assert = require('assert')

describe('open_game', function() {
/*
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('open_game', async function() {
    await driver.get("https://www.yahoo.co.jp/")
    await driver.manage().window().setRect({ width: 945, height: 1140 })
    await driver.findElement(By.css("li:nth-child(20) .fQMqQTGJTbIMxjQwZA2zk")).click()
    await driver.executeScript("window.scrollTo(0,311)")
    await driver.executeScript("window.scrollTo(0,600)")
  })
*/
})
